LPS-81743 Fix split package test failure:
junit.framework.AssertionFailedError: Detected split packages in modules/apps/adaptive-media/adaptive-media-image-service and modules/apps/adaptive-media/adaptive-media-image-impl: [com.liferay.adaptive.media.image.internal.util]
	at com.liferay.portal.split.packages.SplitPackagesTest._checkSplitPackages(SplitPackagesTest.java:138)
	at com.liferay.portal.split.packages.SplitPackagesTest.access$000(SplitPackagesTest.java:42)
	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:95)
	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:64)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.split.packages.SplitPackagesTest.testSplitPackage(SplitPackagesTest.java:62)

(cherry picked from commit 28b4872d07ed99bb1e9ae9ae211230eef6488280)